CREATE TABLE `Company_details` (
  `Id` BIGINT AUTO_INCREMENT,
  `user_id` INT(11) DEFAULT NULL,
  `FirmID` VARCHAR(50)   NOT NULL,
  `RegistrationNo` VARCHAR(100)   DEFAULT NULL,
  `ShopName` VARCHAR(150)   DEFAULT NULL,
  `FirmDescription` TEXT   DEFAULT NULL,
  `Address` TEXT   DEFAULT NULL,
  `State` VARCHAR(100)   DEFAULT NULL,
  `District` VARCHAR(100)   DEFAULT NULL,
  `City` VARCHAR(100)   DEFAULT NULL,
  `Pincode` VARCHAR(20)   DEFAULT NULL,
  `PhoneNumber` VARCHAR(20)   DEFAULT NULL,
  `Email` VARCHAR(100)   DEFAULT NULL,
  `WebsiteName` VARCHAR(100)   DEFAULT NULL,
  `FirmType` VARCHAR(50)   DEFAULT NULL,
  `Comments` TEXT   DEFAULT NULL,
  `WhatsAppLink` VARCHAR(255)   DEFAULT NULL,
  `FacebookLink` VARCHAR(255)   DEFAULT NULL,
  `InstagramLink` VARCHAR(255)   DEFAULT NULL,
  `EnvioceAlPid` VARCHAR(100)   DEFAULT NULL,
  `EnvioceApiKey` VARCHAR(100)   DEFAULT NULL,
  `EnvioceUsername` VARCHAR(100)   DEFAULT NULL,
  `EnviocePassword` VARCHAR(100)   DEFAULT NULL,
  `PaymentBankDetails` TEXT   DEFAULT NULL,
  `AccountHolderName` VARCHAR(255)   DEFAULT NULL,
  `PaymentBankACNo` VARCHAR(50)   DEFAULT NULL,
  `PaymentBankIFSCCode` VARCHAR(50)   DEFAULT NULL,
  `PaymentDeclaration` TEXT   DEFAULT NULL,
  `FinancialYearStartDate` DATE DEFAULT NULL,
  `CashBalance` DECIMAL(18,2) DEFAULT NULL,
  `GSTIN` VARCHAR(50)   DEFAULT NULL,
  `PANNumber` VARCHAR(20)   DEFAULT NULL,
  `PrincipalPalnStart` DECIMAL(18,2) DEFAULT NULL,
  `PrincipalPalnEnd` DECIMAL(18,2) DEFAULT NULL,
  `FormHeader` TEXT   DEFAULT NULL,
  `FormFooter` TEXT   DEFAULT NULL,
  `CompanyLogo` LONGBLOB,
  `FirmLogo` LONGBLOB,
  `OwnerSignature` LONGBLOB,
  `QRcode` LONGBLOB,
  `IsDataPostOnServer` TINYINT(1) DEFAULT NULL,
  `local_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`FirmID`, `local_id`),            -- ✅ Composite Primary Key
  UNIQUE KEY `UNQ_Company_Id` (`Id`)             -- ✅ Unique Auto-increment Id
);
