CREATE TABLE `Diamond_tagging_entry` (
  `Dia_E_D_id` BIGINT AUTO_INCREMENT,
  `Dia_E_Firm_id` VARCHAR(255)   DEFAULT NULL,
  `Dia_E_user_name` VARCHAR(255)   DEFAULT NULL,
  `Dia_E_Stock_Type` VARCHAR(50)   DEFAULT NULL,
  `Dia_E_Particular` VARCHAR(255)   DEFAULT NULL,
  `Dia_E_Party_Name` VARCHAR(150)   DEFAULT NULL,
  `Dia_E_Invoice_No` VARCHAR(100)   DEFAULT NULL,
  `Dia_E_Date` DATE DEFAULT NULL,
  `Dia_E_Image` VARCHAR(255)   DEFAULT NULL,
  `Dia_E_Category` VARCHAR(255)   DEFAULT NULL,
  `Dia_E_SubCategory` VARCHAR(255)   DEFAULT NULL,
  `Dia_E_Design` VARCHAR(255)   DEFAULT NULL,
  `Dia_E_Purity` VARCHAR(50)   DEFAULT NULL,
  `Dia_E_HSN_No` VARCHAR(50)   DEFAULT NULL,
  `Dia_E_HUID_No` VARCHAR(50)   DEFAULT NULL,
  `Dia_E_Size` VARCHAR(50)   DEFAULT NULL,
  `Dia_E_pcs` INT(11) DEFAULT NULL,
  `Dia_E_Gross_wt` DECIMAL(10,3) DEFAULT NULL,
  `Dia_E_Less_wt` INT(20) DEFAULT NULL,
  `Dia_E_Diamond_Ct` DECIMAL(10,3) DEFAULT NULL,
  `Dia_E_Diamond_wt_gm` DECIMAL(10,3) DEFAULT NULL,
  `Dia_E_Net_wt` DECIMAL(10,3) DEFAULT NULL,
  `Dia_E_Diamond_Rate` DECIMAL(10,2) DEFAULT NULL,
  `Dia_E_Diamond_Amt` DECIMAL(10,2) DEFAULT NULL,
  `Dia_E_Net_Rate` DECIMAL(10,2) DEFAULT NULL,
  `Dia_E_Net_Amt` DECIMAL(10,2) DEFAULT NULL,
  `Dia_E_Stone_Ct` DECIMAL(10,3) DEFAULT NULL,
  `Dia_E_Stone_Amt` DECIMAL(10,2) DEFAULT NULL,
  `Dia_E_Description` VARCHAR(255)   DEFAULT NULL,
  `Dia_E_Drop_Down` VARCHAR(100)   DEFAULT NULL,
  `Dia_E_Other_Charges` DECIMAL(10,2) DEFAULT NULL,
  `Dia_E_Value` DECIMAL(10,2) DEFAULT NULL,
  `Dia_E_Final_Amount` DECIMAL(10,2) DEFAULT NULL,
  `Dia_E_Gross_Amount` DECIMAL(10,2) DEFAULT NULL,
  `Dia_E_Remark` VARCHAR(255)   DEFAULT NULL,
  `Dia_E_SrNo` VARCHAR(255)   DEFAULT NULL,
  `Dia_E_Barcode` VARCHAR(255)   DEFAULT NULL,
  `Dia_E_Item_id` INT(11) DEFAULT NULL,
  `Dia_E_Comment` VARCHAR(255)   DEFAULT NULL,
  `local_id` BIGINT(20) NOT NULL,
  `IsDataPostOnServer` TINYINT(1) DEFAULT NULL,

  PRIMARY KEY (`Dia_E_Firm_id`, `local_id`),     -- ✅ Composite primary key
  UNIQUE KEY `UNQ_Dia_E_D_id` (`Dia_E_D_id`)      -- ✅ Dia_E_D_id still unique with AUTO_INCREMENT
);
