CREATE TABLE `Party` (
    `Id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `LocalId` BIGINT NOT NULL,
    `Name` VARCHAR(100) NOT NULL,
    `MobileNumber` VARCHAR(15),
    `Gender` ENUM('Male', 'Female', 'Other'),
    `Email` VARCHAR(100),
    `GSTNumber` VARCHAR(20),
    `PANNumber` VARCHAR(10),
    `Address` TEXT,
    `State` VARCHAR(100),
    `StateCode` VARCHAR(10),
    `District` VARCHAR(100),
    `City` VARCHAR(100),
    `Village` VARCHAR(100),
    `PinCode` VARCHAR(10),
    `AccNo` VARCHAR(20),
    `AccountType` VARCHAR(50),
    `Ifsc` VARCHAR(15),
    `BankName` VARCHAR(100),
    `Branch` VARCHAR(100),
    `Narration` TEXT,
    `CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `IsActive` BOOLEAN DEFAULT TRUE,
    `IsDataPostOnServer` BOOLEAN DEFAULT FALSE,
);

