CREATE TABLE `PurchaseItems` (
  `Id` BIGINT AUTO_INCREMENT,
  `local_id` BIGINT(20) NOT NULL,
  `PurchaseId` INT(11) DEFAULT NULL,
  `firm_id` VARCHAR(20) NOT NULL,
  `Admin_user` VARCHAR(20) DEFAULT NULL,
  `Metal` VARCHAR(50) DEFAULT NULL,
  `HSNCode` VARCHAR(50) DEFAULT NULL,
  `HuidNo` VARCHAR(50) DEFAULT NULL,
  `ItemName` VARCHAR(100) DEFAULT NULL,
  `Purity` VARCHAR(20) DEFAULT NULL,
  `Pcs` INT(11) DEFAULT NULL,
  `GrossWt` DECIMAL(18,3) DEFAULT NULL,
  `Diact` DECIMAL(18,3) DEFAULT NULL,
  `StoneWt` DECIMAL(18,3) DEFAULT NULL,
  `LessWt` DECIMAL(18,3) DEFAULT NULL,
  `NetWt` DECIMAL(18,3) DEFAULT NULL,
  `Rate` DECIMAL(18,2) DEFAULT NULL,
  `amount` DECIMAL(18,2) DEFAULT NULL,
  `stoneCharge` DECIMAL(18,2) DEFAULT NULL,
  `DiaCharge` DECIMAL(18,2) DEFAULT 0.00,
  `Tax_Type` VARCHAR(30) DEFAULT NULL,
  `Tax_Amount` VARCHAR(50) DEFAULT NULL,
  `NetPrice` DECIMAL(18,2) DEFAULT NULL,
  `updated_by` VARCHAR(30) DEFAULT NULL,
  `updated_time` DATE DEFAULT NULL,
  `IsDataPostOnServer` TINYINT(1) DEFAULT NULL,
  PRIMARY KEY (`firm_id`, `local_id`),     -- ✅ Composite primary key
  UNIQUE KEY (`Id`)                         -- ✅ Still keeps `Id` as unique identifier
);
